{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kedy-landing.fullname" . }}
  labels:
    {{- include "kedy-landing.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.clusterIssuer | quote }}
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    {{- if .Values.ingress.redirects.wwwToApex }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ printf "%s-%s-www-redirect@kubernetescrd" .Release.Namespace (include "kedy-landing.fullname" .) | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - secretName: {{ .Values.ingress.tls.secretName }}
      hosts:
        - {{ .Values.ingress.mainHost | quote }}
        {{- if .Values.ingress.wwwHost }}
        - {{ .Values.ingress.wwwHost | quote }}
        {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.mainHost | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "kedy-landing.fullname" . }}
                port:
                  name: http
    {{- if .Values.ingress.wwwHost }}
    - host: {{ .Values.ingress.wwwHost | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "kedy-landing.fullname" . }}
                port:
                  name: http
    {{- end }}
{{- if .Values.ingress.redirects.httpToHttps }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kedy-landing.fullname" . }}-http
  labels:
    {{- include "kedy-landing.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: {{ printf "%s-%s-https-redirect@kubernetescrd" .Release.Namespace (include "kedy-landing.fullname" .) | quote }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.mainHost | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "kedy-landing.fullname" . }}
                port:
                  name: http
    {{- if .Values.ingress.wwwHost }}
    - host: {{ .Values.ingress.wwwHost | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "kedy-landing.fullname" . }}
                port:
                  name: http
    {{- end }}
{{- end }}
{{- end }}
