image:
  repository: docker.io/torchcat/kedy_landing
  tag: v2.0.3
  digest: sha256:4acc3493d65614a333a9dc4940beb6a6871a78fa889e6e2a26e61c8506aa830d

ingress:
  mainHost: kedynsk.ru
  wwwHost: www.kedynsk.ru
  tls:
    clusterIssuer: letsencrypt-prod
    secretName: kedynsk-ru-tls

nodeSelector:
  kubernetes.io/hostname: neurohunter.tech
