image:
  repository: docker.io/torchcat/kedy_landing
  tag: v2.0.1
  digest: sha256:7d7b8129c39a38ef90b34f913d1a45cf543fb32d06f441627fa0f44e5e2a35f7

ingress:
  mainHost: kedynsk.ru
  wwwHost: www.kedynsk.ru
  tls:
    clusterIssuer: letsencrypt-prod
    secretName: kedynsk-ru-tls

nodeSelector:
  kubernetes.io/hostname: neurohunter.tech
