image:
  repository: docker.io/torchcat/kedy_landing
  tag: v2.0.4
  digest: sha256:5d9a37a243812e07f1dc5f69c48e531cdd72bf22cdcdd01a6d62abda62646ed8

ingress:
  mainHost: kedynsk.ru
  wwwHost: www.kedynsk.ru
  tls:
    clusterIssuer: letsencrypt-prod
    secretName: kedynsk-ru-tls

nodeSelector:
  kubernetes.io/hostname: neurohunter.tech
